import type { Academia, TenantBranding, TenantThemeColors, TenantThemePreset } from "./types";

export const TENANT_THEME_PRESETS: Record<TenantThemePreset, TenantThemeColors> = {
  CONCEITO_DARK: {
    accent: "#c8f135",
    primary: "#c8f135",
    ring: "#c8f135",
    secondary: "#1e2026",
    background: "#0e0f11",
    surface: "#16181c",
    border: "#2a2d35",
    foreground: "#eef0f4",
    mutedForeground: "#8a8f9e",
    danger: "#ff5c5c",
    warning: "#ffb347",
    teal: "#3de8a0",
  },
  AZUL_OCEANO: {
    accent: "#38bdf8",
    primary: "#38bdf8",
    ring: "#38bdf8",
    secondary: "#1d2633",
    background: "#0b1220",
    surface: "#121b2b",
    border: "#2b3950",
    foreground: "#e8f2ff",
    mutedForeground: "#91a4c3",
    danger: "#fb7185",
    warning: "#f59e0b",
    teal: "#22d3ee",
  },
  VERDE_ENERGIA: {
    accent: "#22c55e",
    primary: "#22c55e",
    ring: "#22c55e",
    secondary: "#14231b",
    background: "#0a140f",
    surface: "#111d16",
    border: "#284034",
    foreground: "#ebfff1",
    mutedForeground: "#8cbca0",
    danger: "#f97316",
    warning: "#facc15",
    teal: "#14b8a6",
  },
  GRAFITE_FIRE: {
    accent: "#f97316",
    primary: "#f97316",
    ring: "#f97316",
    secondary: "#26201c",
    background: "#14110f",
    surface: "#1d1916",
    border: "#3d322a",
    foreground: "#fff4ec",
    mutedForeground: "#c6a692",
    danger: "#ef4444",
    warning: "#fb923c",
    teal: "#10b981",
  },
  DRACULA: {
    accent: "#bd93f9",
    primary: "#bd93f9",
    ring: "#bd93f9",
    secondary: "#35374b",
    background: "#282a36",
    surface: "#303341",
    border: "#44475a",
    foreground: "#f8f8f2",
    mutedForeground: "#b6b9c8",
    danger: "#ff5555",
    warning: "#ffb86c",
    teal: "#50fa7b",
  },
  AREIA_SOLAR: {
    accent: "#d97706",
    primary: "#f59e0b",
    ring: "#f59e0b",
    secondary: "#f3e7ce",
    background: "#f8f2e7",
    surface: "#fffaf1",
    border: "#dcc9a6",
    foreground: "#3f2d1b",
    mutedForeground: "#7b6650",
    danger: "#dc2626",
    warning: "#f59e0b",
    teal: "#0f766e",
  },
  NUVEM_CLARA: {
    accent: "#2563eb",
    primary: "#3b82f6",
    ring: "#3b82f6",
    secondary: "#dbe7f6",
    background: "#edf4fb",
    surface: "#ffffff",
    border: "#bfd0e3",
    foreground: "#102033",
    mutedForeground: "#5f738a",
    danger: "#dc2626",
    warning: "#d97706",
    teal: "#0891b2",
  },
  ROSA_EDITORIAL: {
    accent: "#db2777",
    primary: "#ec4899",
    ring: "#ec4899",
    secondary: "#f8dbe7",
    background: "#fff1f6",
    surface: "#fff8fb",
    border: "#e7bfd0",
    foreground: "#3f1730",
    mutedForeground: "#7d5a6d",
    danger: "#be123c",
    warning: "#ea580c",
    teal: "#0f766e",
  },
  COBALTO_NOTURNO: {
    accent: "#60a5fa",
    primary: "#3b82f6",
    ring: "#60a5fa",
    secondary: "#18253b",
    background: "#0a1020",
    surface: "#111a2d",
    border: "#263754",
    foreground: "#eaf2ff",
    mutedForeground: "#95a8c8",
    danger: "#f87171",
    warning: "#fbbf24",
    teal: "#22d3ee",
  },
  AURORA_BOREAL: {
    accent: "#2dd4bf",
    primary: "#14b8a6",
    ring: "#2dd4bf",
    secondary: "#162a2b",
    background: "#081617",
    surface: "#0f2022",
    border: "#274347",
    foreground: "#e8fffb",
    mutedForeground: "#90b8b2",
    danger: "#fb7185",
    warning: "#fbbf24",
    teal: "#34d399",
  },
  TERRACOTA_SUAVE: {
    accent: "#c2410c",
    primary: "#ea580c",
    ring: "#ea580c",
    secondary: "#f1ddd3",
    background: "#fcf4ef",
    surface: "#fffaf7",
    border: "#dfc2b3",
    foreground: "#45261d",
    mutedForeground: "#7a5d53",
    danger: "#dc2626",
    warning: "#d97706",
    teal: "#0f766e",
  },
  MENTA_MODERNA: {
    accent: "#10b981",
    primary: "#10b981",
    ring: "#10b981",
    secondary: "#dcefe9",
    background: "#f2fbf8",
    surface: "#ffffff",
    border: "#beded3",
    foreground: "#16332b",
    mutedForeground: "#5c7a71",
    danger: "#dc2626",
    warning: "#ca8a04",
    teal: "#0f766e",
  },
};

export const TENANT_THEME_OPTIONS: Array<{ id: TenantThemePreset; nome: string; descricao: string }> = [
  { id: "CONCEITO_DARK", nome: "Conceito Dark", descricao: "Visual escuro padrão do sistema" },
  { id: "AZUL_OCEANO", nome: "Azul Oceano", descricao: "Tom moderno com foco em tecnologia" },
  { id: "VERDE_ENERGIA", nome: "Verde Energia", descricao: "Perfil fitness com destaque em saúde" },
  { id: "GRAFITE_FIRE", nome: "Grafite Fire", descricao: "Contraste quente para vendas e conversão" },
  { id: "DRACULA", nome: "Dracula", descricao: "Paleta clássica arroxeada com contraste alto para uso noturno" },
  { id: "AREIA_SOLAR", nome: "Areia Solar", descricao: "Tema claro com dourado quente e base editorial" },
  { id: "NUVEM_CLARA", nome: "Nuvem Clara", descricao: "Tema claro azulado com aparência limpa e corporativa" },
  { id: "ROSA_EDITORIAL", nome: "Rosa Editorial", descricao: "Tema claro sofisticado com acento magenta" },
  { id: "COBALTO_NOTURNO", nome: "Cobalto Noturno", descricao: "Escuro frio com foco em dashboards e tecnologia" },
  { id: "AURORA_BOREAL", nome: "Aurora Boreal", descricao: "Escuro esverdeado com contraste vibrante e moderno" },
  { id: "TERRACOTA_SUAVE", nome: "Terracota Suave", descricao: "Tema claro terroso para marcas mais humanas" },
  { id: "MENTA_MODERNA", nome: "Menta Moderna", descricao: "Tema claro fresco com leitura leve e clean" },
];

export const DEFAULT_THEME_PRESET: TenantThemePreset = "CONCEITO_DARK";
export const DEFAULT_TENANT_APP_NAME = "Conceito Fit";

export function resolveTenantTheme(academia?: Academia): TenantThemeColors {
  const preset = academia?.branding?.themePreset ?? DEFAULT_THEME_PRESET;
  const base = TENANT_THEME_PRESETS[preset] ?? TENANT_THEME_PRESETS[DEFAULT_THEME_PRESET];
  if (!academia?.branding?.useCustomColors) return base;
  return {
    ...base,
    ...(academia.branding?.colors ?? {}),
  };
}

export function getTenantAppName(academia?: Academia): string {
  return academia?.branding?.appName?.trim() || academia?.nome?.trim() || DEFAULT_TENANT_APP_NAME;
}

export function createDefaultBranding(): TenantBranding {
  return {
    appName: DEFAULT_TENANT_APP_NAME,
    themePreset: DEFAULT_THEME_PRESET,
    useCustomColors: false,
  };
}
